### ISSUE TITLE
**Bug: `L.markerClusterGroup is not a function` in v14, works in v13.1**

### ISSUE THREAD

**Issue by Pjarbit** [nathan-gs/ha-map-card#195]
**Describe the bug**
After updating map-card to v14, the card fails to load with the following console error:

```
TypeError: L.markerClusterGroup is not a function
  at EntitiesRenderService.setup
  at MapCard.setup
  at MapCard.firstUpdated
```

The card briefly renders on soft navigation but fails on hard refresh (Ctrl+Shift+R). Rolling back to v13.1 resolves the issue completely.

**To Reproduce**
1. Install map-card v14 via HACS
2. Add a map card with entity tracking
3. Hard refresh the browser
4. Observe the error in console and "Error found in first run" message on the card

**Expected behavior**
Map card loads correctly with marker clustering, as it did in v13.1.

**Workaround**
Downgrade to v13.1 via HACS.

**Environment**
- map-card version: v14 (broken), v13.1 (working)
- Home Assistant version: March 2026 version 4
- Browser: chrome

Installation method     Home Assistant OS
Core                             2026.3.4
Supervisor                   2026.03.3
Operating System       17.2
Frontend                      20260312.1

**Comment by vingerha** [comment]
Adding console error, sticking to 1.13 version for now

<img width="1061" height="374" alt="Image" src="https://github.com/user-attachments/assets/dc5cd1af-a40e-4a88-a9de-1049e6d259aa" />

**Comment by franchiceddhu** [comment]
Can confirm, same to me. Funny enough, when opened from PC rather than mobile, it kinda fixed itself and there are no errors shown in console. Yet, "cluster_markers: false" won't work; markers will always be clustered.

**Comment by Pjarbit** [comment]
Writing an integration is not easy and a ton of work.  Even when you're satisfied and happy, some idiot (like me) writes and complains "its not working". This is a quick note to say I appreciate you and all the hard work you put in to make this card and maintain it! Thank you.
Phil Arbit
